/**
 * Customer API
 * This is a customer api created using swagger
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ranjani.vraman@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.Customer
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Get customer
   * 
   * Expected answers:
   *   code 200 : Customer (response for customer)
   *   code 404 :  (employee with this id doesnot exist)
   * 
   * @param customerId ?customerId&#x3D;
   */
  def getCustomer(customerId: Int): ApiRequest[Customer] =
    ApiRequest[Customer](ApiMethods.GET, "http://missguided.admin.com/customersupport/v1", "/customer", "application/json")
      .withQueryParam("customerId", customerId)
      .withSuccessResponse[Customer](200)
      .withErrorResponse[Unit](404)
        /**
   * Add customer
   * 
   * Expected answers:
   *   code 200 : Int (response for customer)
   *   code 405 :  (Input invaid)
   * 
   * @param cusotmerJson customer details in json
   */
  def postCustomer(cusotmerJson: Customer): ApiRequest[Int] =
    ApiRequest[Int](ApiMethods.POST, "http://missguided.admin.com/customersupport/v1", "/customer", "application/json")
      .withBody(cusotmerJson)
      .withSuccessResponse[Int](200)
      .withErrorResponse[Unit](405)
      

}

