/**
 * Customer API
 * This is a customer api created using swagger
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ranjani.vraman@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.api

import io.swagger.client.model.InlineResponse200
import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object DefaultApi {

  /**
   * Get customer
   * 
   * Expected answers:
   *   code 200 : InlineResponse200 (response for customer)
   * 
   * @param customerId ?customerId&#x3D;
   */
  def getCustomer(customerId: Int): ApiRequest[InlineResponse200] =
    ApiRequest[InlineResponse200](ApiMethods.GET, "https://localhost", "/customer", "application/json")
      .withQueryParam("customerId", customerId)
      .withSuccessResponse[InlineResponse200](200)
      

}

