/**
 * Customer API
 * This is a customer api created using swagger
 *
 * OpenAPI spec version: 1.0.0
 * Contact: ranjani.vraman@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model

import io.swagger.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class InlineResponse200 (
  customerId: Option[Int] = None,
  accountValue: Option[Double] = None,
  active: Option[Boolean] = None,
  contacts: Option[Seq[InlineResponse200Contacts]] = None
) extends ApiModel


